### ISSUE TITLE
Rock aint rocking

### ISSUE THREAD

**Issue by shawshankkumar** [calcom/cal.fm#2]
https://github.com/calcom/cal.fm/blob/main/index.html#L91

<img width="1792" alt="image" src="https://github.com/calcom/cal.fm/assets/74819565/b694ecb8-dea1-445f-b6aa-54828bce74ce">

**Comment by Sumit21kumar** [comment]
its working

**Comment by connectwithpankaj** [comment]
Its working on my local device. The page is opening smoothly without any issue.

**Comment by shawshankkumar** [comment]
it got fixed folks.
